# Generated by Django 2.2.27 on 2022-04-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
